
runtime: nodejs12
env: standard

# manual_scaling:
#   instances: 1
# resources:
#   cpu: 1
#   memory_gb: 0.5
#   disk_size_gb: 10

env_variables:
  CLOUD_SQL_CONNECTION_NAME: zaply-295212:southamerica-east1:zaply-dummy-products
